---
abstract: 'Catalyst SCGI Engine'
author: Orlando Vazquez
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catalyst-Engine-SCGI
no_index:
  directory:
    - inc
    - t
requires:
  Catalyst: 5.8
  SCGI: 0
resources:
  repository: http://github.com/orlandov/Catalyst-Engine-SCGI
version: 0.02
